-- Creating CART Table
CREATE TABLE CART (
    CART_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEMS NUMERIC(15) NOT NULL,
    WISHLISTED INT,
    DELIVERY_DATE DATE NOT NULL
);

-- Creating DOC_CONSULT Table
CREATE TABLE DOC_CONSULT (
    DOC_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DOC_NAME VARCHAR(50) NOT NULL,
    QUALIFICATION VARCHAR(100) NOT NULL,
    SPECIALIZATION VARCHAR(100) NOT NULL,
    PHONE_NO NUMERIC(10,0) NOT NULL CHECK (PHONE_NO BETWEEN 5555555555 AND 9999999999)
);

-- Creating MEDICINE_SHOP Table
CREATE TABLE MEDICINE_SHOP (
    SHOP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SHOP_NAME VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100),
    PHONE_NO NUMERIC(10,0) NOT NULL CHECK (PHONE_NO BETWEEN 5555555555 AND 9999999999)
);

-- Creating PRODUCTS Table
CREATE TABLE PRODUCTS (
    PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(20) NOT NULL,
    QTY NUMERIC(4) NOT NULL,
    GENDER VARCHAR(7) NOT NULL,
    AGE_GROUP VARCHAR(20) CHECK(AGE_GROUP IN ('INFANT', 'CHILDREN', 'ADULT')),
    COST NUMERIC(5,2) NOT NULL,
    COMMISSION_PERCENT NUMERIC(3,2) NOT NULL,
    SHOP_ID BIGINT,
    FOREIGN KEY (SHOP_ID) REFERENCES MEDICINE_SHOP(SHOP_ID)
);

-- Creating CUSTOMER Table
CREATE TABLE CUSTOMER (
    CUST_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUST_NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100),
    PINCODE NUMERIC(6,0) CHECK (PINCODE BETWEEN 100000 AND 999999),
    PHONE_NO NUMERIC(10,0) CHECK (PHONE_NO BETWEEN 5555555555 AND 9999999999),
    GENDER VARCHAR(7),
    DOC_ID BIGINT,
    CART_ID BIGINT,
    CONSTRAINT GENDER_CONSTRAINT CHECK(GENDER IN ('MALE', 'FEMALE')),
    FOREIGN KEY (CART_ID) REFERENCES CART (CART_ID),
    FOREIGN KEY (DOC_ID) REFERENCES DOC_CONSULT (DOC_ID) ON DELETE CASCADE
);

-- Creating PAYMENT Table
CREATE TABLE PAYMENT (
    PAYMENT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PAYMENT_DATE DATE,
    COUPON_APPLIED VARCHAR(4) CHECK(COUPON_APPLIED IN ('YES', 'NO')),
    TOTAL_AMT NUMERIC(6,2),
    PAYMENT_METHOD VARCHAR(50) CHECK(PAYMENT_METHOD IN ('CASH ON DELIVERY', 'CREDIT/DEBIT CARD', 'E-WALLETS', 'NETBANKING')),
    CART_ID BIGINT,
    CUST_ID BIGINT,
    SHOP_ID BIGINT,
    FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID),
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID),
    FOREIGN KEY (SHOP_ID) REFERENCES MEDICINE_SHOP(SHOP_ID) ON DELETE CASCADE
);

-- Inserting Sample Data
INSERT INTO DOC_CONSULT (DOC_NAME, QUALIFICATION, SPECIALIZATION, PHONE_NO) VALUES
('VD MAHESHWARI', 'MBBS, MD', 'GENERAL PHYSICIAN', 9864576631),
('SUSHMA BHARADWAJ', 'MBBS', 'GYNAECOLOGIST', 8291244699);

INSERT INTO MEDICINE_SHOP (SHOP_NAME, ADDRESS, PHONE_NO) VALUES
('KISHORE MEDICINES', 'BMC HOSPITAL ROAD, BANGALORE', 9878773331);

INSERT INTO PRODUCTS (TYPE, QTY, GENDER, AGE_GROUP, COST, COMMISSION_PERCENT) VALUES
('GENERAL MEDICINE', 100, 'MALE', 'ADULT', 300.0, 20.00);

INSERT INTO CUSTOMER (CUST_NAME, ADDRESS, PINCODE, PHONE_NO) VALUES
('Rishabh Dev', 'Rajaji Nagar', 560010, 9234511234);

INSERT INTO PAYMENT (PAYMENT_DATE, COUPON_APPLIED, TOTAL_AMT, PAYMENT_METHOD) VALUES
('2019-04-20', 'YES', 5100.45, 'CREDIT/DEBIT CARD');

-- Procedure to Add a New Customer
DELIMITER $$
CREATE PROCEDURE AddNewCustomer (
    IN p_CUST_NAME VARCHAR(50),
    IN p_ADDRESS VARCHAR(100),
    IN p_PINCODE DECIMAL(6,0),
    IN p_PHONE_NO DECIMAL(10,0)
)
BEGIN
    INSERT INTO CUSTOMER (CUST_NAME, ADDRESS, PINCODE, PHONE_NO)
    VALUES (p_CUST_NAME, p_ADDRESS, p_PINCODE, p_PHONE_NO);
END $$
DELIMITER ;

-- Creating a Trigger
CREATE TABLE ENTRY_LOG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ENTRY_DATE TIMESTAMP NOT NULL
);

DELIMITER //
CREATE TRIGGER medical_entry_trigger
AFTER INSERT ON MEDICINE_SHOP
FOR EACH ROW
BEGIN
    INSERT INTO ENTRY_LOG (ENTRY_DATE) VALUES (NOW());
END //
DELIMITER ;

-- Sample Queries
SELECT * FROM PRODUCTS WHERE COST > 200;
SELECT AGE_GROUP, AVG(COST) AS AVERAGE_COST FROM PRODUCTS GROUP BY AGE_GROUP;
SELECT COUNT(*) AS E_WALLET_CUSTOMERS FROM CUSTOMER WHERE CUST_ID IN (SELECT CUST_ID FROM PAYMENT WHERE PAYMENT_METHOD = 'E-WALLETS');
